config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  unauthenticated do
    root to: 'home#index', as: 'home_root'
  end

  root 'groups#index'

  resources :groups do
    resources :entities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, foreign_key: :author_id
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :entities

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups
  has_many :entities, foreign_key: :author_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_group
  before_action :set_entity, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /entities or /entities.json
  def index
    @entities = @group&.entities&.order(created_at: :desc) || []
    @total_amount = @group&.entities&.sum(:amount) || 0
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)
    @entity.author_id = current_user.id
    @entity.user_id = current_user.id

    respond_to do |format|
      if @entity.save
        # Add the entity to the selected group
        if params[:entity][:group_id].present?
          @group = Group.find_by(id: params[:entity][:group_id])
          @entity.groups << @group if @group.present?
        end

        format.html { redirect_to group_path(@group), notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  def set_group
    @group = Group.find_by(id: params[:group_id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /groups or /groups.json
  def index
    @user = current_user
    @groups = @user.groups.all || []

    @group_amounts = {}
    @groups.each do |group|
      total_amount = group.entities.sum(:amount)
      @group_amounts[group.id] = total_amount
    end
  end

  # GET /groups/1 or /groups/1.json
  def show
    redirect_to group_entities_path(@group)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>" class="border p-4 mx-2 mb-4 cursor-pointer bg-white">
  <div class="flex items-center mb-2">
    <div>
      <p class="text-lg font-semibold"><%= entity.name %></p>
    </div>
    <div class="ml-auto">
      <strong> <%= entity.amount %> $</strong> 
    </div>
  </div>
</div>

app/views/entities/_form.html.erb
<%= form_with(model: @entity, url: group_entities_path(@group)) do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form.hidden_field :group_id, value: @group.id %>

  <div class="flex flex-col items-center">
    <div class="w-full max-w-md">
      <label class="block text-black mb-2" for="group_name">Transaction Name:</label>
      <%= form.text_field :name, class: "border border-black p-2 mb-4 w-full", placeholder: "Transaction Name", id: "group_name" %>

      <label class="block text-black mb-2" for="group_icon">Amount:</label>
      <%= form.number_field :amount, class: "border border-black p-2 mb-4 w-full", placeholder: "Amount", id: "group_icon" %>

      <label class="block text-black mb-2" for="group_icon">Available Categories:</label>
      <%= form.collection_select :group_id, current_user.groups, :id, :name, class: "border border-black p-2 mb-4", id: "group_icon" %>
    
    </div>

    <%= form.submit "Create Transaction", class: "bg-green-500 text-white px-4 py-2 rounded-lg mt-4 hover:bg-green-600 cursor-pointer" %>
  </div>
<% end %>

app/views/entities/index.html.erb
<nav class="bg-blue-500 py-4">
  <div class="container mx-auto px-4 flex justify-between items-center">
    <div>
      <%= link_to(groups_path, class: "text-white py-2 rounded-lg hover:bg-blue-700") do %>
        <i class="fas fa-arrow-left mr-2"></i><% end %>
    </div>

    <!-- Centered page heading -->
    <div class="flex-1 text-center text-white text-2xl font-semibold">
      Transactions
    </div>
  </div>
</nav>

<div class="container mx-auto p-4 m-4 bg-white">
  <div class="text-center text-lg font-semibold">
    Total Amount of Transaction: <%= @total_amount %> $
  </div>
</div>

<div id="entities">
  <p style="color: green"><%= notice %></p>
  <% if @entities.any? %>
    <% @entities.each do |entity| %>
      <%= render partial: 'entity', locals: { entity: entity } %>
    <% end %>
  <% else %>
    <p>No entities available right now.</p>
  <% end %>
</div>

<div class="bg-green-500 text-white py-4 fixed bottom-0 w-full">
  <div class="container mx-auto text-center">
    <a href="<%= new_group_entity_path(@group) %>" class="text-white text-xl px-4 py-2">Add new Transaction</a>
  </div>
</div>

app/views/entities/new.html.erb
<nav class="bg-blue-500 py-4">
  <div class="container mx-auto px-4 flex justify-between items-center">

    <div>
      <%= link_to(group_entities_path, class: "text-white px-2 py-2 rounded-lg hover:bg-blue-700") do %>
        <i class="fas fa-arrow-left mr-2"></i><% end %>
    </div>

    <!-- Centered page heading -->
    <div class="flex-1 text-center text-white text-2xl font-semibold">
      Add New Transaction
    </div>
  </div>
</nav>

<%= render "form", entity: @entity %>

app/views/groups/_form.html.erb
<%= form_with(model: @group, url: groups_path, class: "container mx-auto mt-4") do |form| %>
  <p style="color: green"><%= notice %></p>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col items-center">
    <div class="w-full max-w-md">
      <label class="block text-black mb-2" for="group_name">Category Name:</label>
      <%= form.text_field :name, class: "border border-black p-2 mb-4 w-full", placeholder: "Category Name", id: "group_name" %>

      <label class="block text-black mb-2" for="group_icon">Icon URL:</label>
      <%= form.text_field :icon, class: "border border-black p-2 mb-4 w-full", placeholder: "Icon URL", id: "group_icon" %>
    </div>

    <%= form.submit "Create Category", class: "bg-green-500 text-white px-4 py-2 rounded-lg mt-4 hover:bg-green-600 cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="border p-4 mb-4 cursor-pointer bg-white" onclick="window.location.href='<%= group_path(group) %>';">
  <div class="flex items-center mb-2">
    <div class="mr-2">
      <img src="<%= group.icon %>" alt="Group Icon" class="w-8 h-8 rounded-full">
    </div>
    <div>
      <p class="text-lg font-semibold"><%= group.name %></p>
      
    </div>
    <div class="ml-auto">
      <p>Total Amount: <%= @group_amounts[group.id] %> $</p>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<nav class="bg-blue-500 py-4 px-1">
  <div class="container mx-auto px-2 flex justify-between items-center">
    <!-- Toggle button (on the left corner) -->
    <button class="text-white">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Centered page heading -->
    <div class="text-center text-white text-2xl font-semibold">
      Categories
    </div>

    <!-- Logout button on the right corner -->
    <div>
  <%= button_to 'Log Out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to sign out?' }, class: "text-white font-semibold" %>
</div>
  </div>
</nav>

<div class="container mx-auto mt-4">
  <p style="color: green"><%= notice %></p>

  <div id="groups">
    <% @groups.each do |group| %>
      <%= render partial: 'group', locals: { group: group } %>
    <% end %>
  </div>
</div>

<div class="bg-green-500 text-white py-4 fixed bottom-0 w-full">
  <div class="container mx-auto text-center">
    <a href="<%= new_group_path %>" class="text-white text-xl px-4 py-2">Add new Category</a>
  </div>
</div>

app/views/groups/new.html.erb
<nav class="bg-blue-500 py-4">
  <div class="container mx-auto px-4 flex justify-between items-center">

    <div>
      <%= link_to(groups_path, class: "text-white px-2 py-2 rounded-lg hover:bg-blue-700") do %>
        <i class="fas fa-arrow-left mr-2"></i><% end %>
    </div>

    <!-- Centered page heading -->
    <div class="flex-1 text-center text-white text-2xl font-semibold">
      Add New Category
    </div>
  </div>
</nav>


<%= render "form", group: @group %>

<br>

app/views/home/index.html.erb
<div class="min-h-screen flex flex-col items-center justify-center bg-gray-100">
  <div class="flex flex-col items-center justify-center flex-grow"> <!-- Adjusted this line -->
    <h3 class="text-3xl font-semibold text-center mb-4">Budget App</h3>
    <p class="text-center text-gray-600 mb-8">A simple and effective budget management tool.</p>
  </div>
  <div class="mt-auto w-full">
    <div class="flex flex-col items-center md:flex-row md:justify-center">
      <%= link_to "LOG IN", new_user_session_path, class: "bg-blue-500 text-white px-4 py-4 hover:bg-blue-600 w-full md:w-auto text-center md:text-left mb-2 md:mb-0 md:mr-2" %>
      <%= link_to "SIGN UP", new_user_registration_path, class: "bg-silver-500 text-black-100 px-4 py-4 hover:bg-blue-600 w-full md:w-auto text-center md:text-left" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCapstoneBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

  </head>

  <body>
    <%= yield %>
    <p class="p-3 alert"><%= alert %></p>
  </body>
</html>